default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.10.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.0a3
    hooks:
      - id: sqlfluff-fix
        args: [-q]
        stages: [pre-commit]
        exclude: schema.sql
      - id: sqlfluff-lint
        stages: [pre-commit]
        exclude: schema.sql
  - repo: https://github.com/TekWizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: golangci-lint-repo-mod
        stages: [pre-commit]
        args: [--fix]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.54.0
    hooks:
      - id: eslint
        stages: [pre-commit]
        additional_dependencies:
          - eslint@8.53.0
          - eslint-plugin-react-hooks@4.6.0
          - eslint-plugin-react-refresh@0.4.3
          - eslint-config-airbnb@19.0.4
          - eslint-config-standard-with-typescript@39.1.1
          - eslint-config-airbnb-typescript@17.1.0
        exclude: node_modules
        files: \.[t]sx?$ # *.ts and *.tsx
        types: [file]
        args: [--max-warnings=0, --fix]
