repos:
  - repo: https://github.com/Cielquan/commit-msg-jira-hook
    rev: v1.0.0
    hooks:
    - id: jira_prepare_commit_msg
      args: [--jira-tag=TEA]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.53.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.53.0
          - eslint-plugin-react-hooks@4.6.0
          - eslint-plugin-react-refresh@0.4.3
          - eslint-config-airbnb@19.0.4
          - eslint-config-standard-with-typescript@39.1.1
          - eslint-config-airbnb-typescript@17.1.0
        exclude: node_modules
        files: \.[t]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        args: [--max-warnings=1, --fix]
