volumes:
  communitea-db:
    external: true

services:
  postgres:
    image: postgres:14.5-bullseye
    volumes:
      - communitea-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: admin
      POSTGRES_DB: communitea-db
    ports:
      - 15432:5432

  goapi:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    command: bash -c "sqlc generate && air /cmd/main.go -b 0.0.0.0"

  webapp:
    image: node:lts-bullseye
    env_file:
      - .env
    # Change the run dev command to run build for production
    command: bash -c "npm install && npm run dev"
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
