// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: businesses.sql

package db

import (
	"context"
)

const getAllBusinesses = `-- name: GetAllBusinesses :many
select id, name, street_address, city, state, zipcode, business_owner_id from businesses
`

func (q *Queries) GetAllBusinesses(ctx context.Context) ([]Business, error) {
	rows, err := q.db.Query(ctx, getAllBusinesses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Business{}
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StreetAddress,
			&i.City,
			&i.State,
			&i.Zipcode,
			&i.BusinessOwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
