// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: events.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getEventByID = `-- name: GetEventByID :one
select
    "id",
    "name",
    "host",
    "location_name",
    "street_address",
    "city",
    "state",
    "zipcode",
    "date",
    "start_time",
    "end_time",
    "md_description",
    "html_description",
    "rsvps",
    "capacity"
from events
where "id" = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.LocationName,
		&i.StreetAddress,
		&i.City,
		&i.State,
		&i.Zipcode,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
		&i.MdDescription,
		&i.HtmlDescription,
		&i.Rsvps,
		&i.Capacity,
	)
	return i, err
}
