// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: locations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCity = `-- name: CreateCity :one
insert into locations_cities ("id", "name", "state")
values ($1, $2, $3)
returning id, name, state
`

type CreateCityParams struct {
	ID    pgtype.UUID `json:"id"`
	Name  string      `json:"name"`
	State string      `json:"state"`
}

func (q *Queries) CreateCity(ctx context.Context, arg CreateCityParams) (LocationsCity, error) {
	row := q.db.QueryRow(ctx, createCity, arg.ID, arg.Name, arg.State)
	var i LocationsCity
	err := row.Scan(&i.ID, &i.Name, &i.State)
	return i, err
}

const getAllCities = `-- name: GetAllCities :many
select id, name, state from locations_cities
`

func (q *Queries) GetAllCities(ctx context.Context) ([]LocationsCity, error) {
	rows, err := q.db.Query(ctx, getAllCities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LocationsCity{}
	for rows.Next() {
		var i LocationsCity
		if err := rows.Scan(&i.ID, &i.Name, &i.State); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCity = `-- name: GetCity :one
select "id" from locations_cities
where ("name" = 'string')
limit 1
`

// ! THIS IS A DEBUG QUERY: DELETE FOR PROD
func (q *Queries) GetCity(ctx context.Context) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getCity)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
