// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type LocationsCity struct {
	ID    pgtype.UUID `json:"id"`
	Name  string      `json:"name"`
	State string      `json:"state"`
}

type LocationsState struct {
	Name         string `json:"name"`
	Abbreviation string `json:"abbreviation"`
}

type User struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}
