// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
insert into users
values ($1, $2, $3, $4, $5, $6, $7, $8)
returning id, role, username, first_name, last_name, email, password, location
`

type CreateUserParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 pgtype.Text `json:"column_2"`
	Column3 pgtype.Text `json:"column_3"`
	Column4 pgtype.Text `json:"column_4"`
	Column5 pgtype.Text `json:"column_5"`
	Column6 pgtype.Text `json:"column_6"`
	Column7 []byte      `json:"column_7"`
	Column8 pgtype.UUID `json:"column_8"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.Location,
	)
	return i, err
}

const login = `-- name: Login :one
select
    "id",
    "role",
    "username",
    "first_name",
    "last_name",
    "location",
    "password"
from users
where "username" = $1
`

type LoginRow struct {
	ID        pgtype.UUID `json:"id"`
	Role      string      `json:"role"`
	Username  string      `json:"username"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	Location  pgtype.UUID `json:"location"`
	Password  []byte      `json:"password"`
}

func (q *Queries) Login(ctx context.Context, username string) (LoginRow, error) {
	row := q.db.QueryRow(ctx, login, username)
	var i LoginRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Location,
		&i.Password,
	)
	return i, err
}
