name: Verify Backend Build

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'backend/**'
      - '!backend/db/**'

# Cancel the workflow in progress if newer build is about to start.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  checks: write
  pull-requests: write

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Backend Folder
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            backend
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          working-directory: backend

  backend-unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout Backend Folder
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            backend
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: Install dependencies
        run: go mod tidy
      - name: Build app
        run: go build -v cmd
      - name: Run unit tests w/ coverage report
        run: go test backend/cmd/.. -args -race -coverprofile+coverage.out -covermode=atomic
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          flags: backend
