name: Backend CD

on:
  push:
    branches: ['main']
    paths:
      - 'backend/**'

# Cancel the workflow in progress if newer build is about to start.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    outputs:
      artifact-id: ${{ steps.artifact-upload.outputs.artifact-id }}
    steps:
      - name: Checkout 'backend' folder
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            backend
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
      - name: Install dependencies
        run: go mod tidy
      - name: Create directory for build output
        run: mkdir tmp
      - name: Build app
        run: GOOS=linux GOARCH=amd64 go build -ldflags "-X main.Env=prod" -v -o ./tmp ./cmd
      - name: Upload build as artifact
        uses: actions/upload-artifact@v4
        id: artifact-upload
        with:
          name: app-artifact
          path: 'backend/tmp'
          if-no-files-found: error
          retention-days: 1

  ping-api-server:
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - name: Invoke webhook
        uses: johannes-huther/webhook.sh@v1
        env:
          webhook_url: ${{ secrets.BACKEND_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{"artifact-id": "${{ needs.build-backend.outputs.artifact-id }}"}'
