name: Lint API Application

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'backend/**'
      - '!backend/db/**'

# Cancel the workflow in progress if newer build is about to start.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  checks: write

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Backend Folder
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            backend
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          working-directory: backend
